spring:
  application:
    name: internship-backend

  datasource:
    # Замени на свои данные из Supabase
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.gexxcdtarifagzqjmvbu
    password: 135792468dosZhAn!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # При запуске будет обновлять схему БД под твои Entity
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

integrations:
  egov-schools:
    base-url: https://data.egov.kz/api/v4/onirler_oblystar_kalalar_boi4/v3
    api-key: 6a12931d7ce1433485f4e1b4f1f83929
